# Generated by Django 4.2.2 on 2023-06-30 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportingForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "type_of_vulnerability",
                    models.CharField(
                        choices=[
                            ("Injection", "Injection"),
                            ("Broken Authentication", "Broken Authentication"),
                            ("Sensitive data exposure", "Sensitive data exposure"),
                            (
                                "XML External Entities (XXE)",
                                "XML External Entities (XXE)",
                            ),
                            (
                                "Security misconfigurations",
                                "Security misconfigurations",
                            ),
                            (
                                "Cross Site Scripting (XSS)",
                                "Cross Site Scripting (XSS)",
                            ),
                            ("Broken Access control", "Broken Access control"),
                            ("Insecure Deserialization", "Insecure Deserialization"),
                            ("Availability", "Availability"),
                            ("Integrity", "Integrity"),
                            ("Confidentiality", "Confidentiality"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Public User", "Public User"),
                            ("Employee", "Employee"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
