# Generated by Django 4.2.2 on 2023-07-03 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "type_of_vulnerability",
                    models.CharField(
                        choices=[
                            ("Injection", "Injection"),
                            ("Broken Authentication", "Broken Authentication"),
                            ("Sensitive data exposure", "Sensitive data exposure"),
                            (
                                "XML External Entities (XXE)",
                                "XML External Entities (XXE)",
                            ),
                            (
                                "Security misconfigurations",
                                "Security misconfigurations",
                            ),
                            (
                                "Cross Site Scripting (XSS)",
                                "Cross Site Scripting (XSS)",
                            ),
                            ("Broken Access control", "Broken Access control"),
                            ("Insecure Deserialization", "Insecure Deserialization"),
                            ("Availability", "Availability"),
                            ("Integrity", "Integrity"),
                            ("Confidentiality", "Confidentiality"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="VulnerabilityFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Injection", "Injection"),
                            ("Broken Authentication", "Broken Authentication"),
                            ("Sensitive data exposure", "Sensitive data exposure"),
                            (
                                "XML External Entities (XXE)",
                                "XML External Entities (XXE)",
                            ),
                            (
                                "Security misconfigurations",
                                "Security misconfigurations",
                            ),
                            (
                                "Cross Site Scripting (XSS)",
                                "Cross Site Scripting (XSS)",
                            ),
                            ("Broken Access control", "Broken Access control"),
                            ("Insecure Deserialization", "Insecure Deserialization"),
                            ("Availability", "Availability"),
                            ("Integrity", "Integrity"),
                            ("Confidentiality", "Confidentiality"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("Critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
