# Generated by Django 4.2.2 on 2023-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportingform",
            name="user_type",
        ),
    ]
