# Generated by Django 4.2.2 on 2023-07-04 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingForm2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('type_of_vulnerability', models.CharField(choices=[('Injection', 'Injection'), ('Broken Authentication', 'Broken Authentication'), ('Sensitive data exposure', 'Sensitive data exposure'), ('XML External Entities (XXE)', 'XML External Entities (XXE)'), ('Security misconfigurations', 'Security misconfigurations'), ('Cross Site Scripting (XSS)', 'Cross Site Scripting (XSS)'), ('Broken Access control', 'Broken Access control'), ('Insecure Deserialization', 'Insecure Deserialization'), ('Availability', 'Availability'), ('Integrity', 'Integrity'), ('Confidentiality', 'Confidentiality')], max_length=30)),
                ('explanation_of_vulnerability', models.TextField(max_length=255)),
                ('why_is_it_a_vulnerability', models.TextField(max_length=255)),
                ('domain_name_or_ip_address', models.CharField(max_length=255)),
            ],
        ),
    ]
