# Generated by Django 4.2.2 on 2023-07-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting_system", "0002_reportingform2model"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingform2model",
            name="status",
            field=models.CharField(
                choices=[("unfixed", "Unfixed"), ("fixed", "Fixed")],
                default="unfixed",
                max_length=10,
            ),
        ),
    ]
