"""
Django settings for dfrs_domain project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants as messages
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# (Set to True when in development mode)
DEBUG = True

ALLOWED_HOSTS = [
    "dfrsdomain-production.up.railway.app",
    "dfrsdomain-dev.up.railway.app",
    "127.0.0.1"
]

CSRF_TRUSTED_ORIGINS = [
    "https://dfrsdomain-production.up.railway.app",
    "https://dfrsdomain-dev.up.railway.app",
    "https://127.0.0.1"
]

# Uncomment For Debugging Only
# INTERNAL_IPS = [
#     # ...
#     "127.0.0.1",
#     # ...
# ]

# Security settings
SECURE_HSTS_SECONDS = 31536000
SECURE_CONTENT_TYPE_NOSNIFF = True
# using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
SESSION_COOKIE_SECURE=True
# Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
CSRF_COOKIE_SECURE=True

# For Production ONLY
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# # Security settings
# SECURE_HSTS_SECONDS = 31536000
# SECURE_CONTENT_TYPE_NOSNIFF = True
# # Forces application to be servered over a SSL connection only
# # (Set to False when in development mode)
# SECURE_SSL_REDIRECT=True
# # using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
# SESSION_COOKIE_SECURE=True
# # Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
# CSRF_COOKIE_SECURE=True
# # Makes sure all subdomains are served over SSL 
# SECURE_HSTS_INCLUDE_SUBDOMAINS=True
# # Adds site to browser preload list
# SECURE_HSTS_PRELOAD=True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "reporting_system.apps.ReportingSystemConfig",
    "user_service.apps.UserServiceConfig",
    "crispy_forms",
    "crispy_tailwind",
    "eventlog.apps.EventLogConfig",
    # "debug_toolbar",  # Uncomment For Debugging Only
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dfrs_domain.middleware.RestrictAdminMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware", # Uncomment For Debugging Only

]
AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
    )
ROOT_URLCONF = "dfrs_domain.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dfrs_domain.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
db_config = dj_database_url.config(default=os.environ.get('DATABASE_URL'), conn_max_age=1000,
                                   ssl_require=True, engine="django_cockroachdb")
DATABASES = {
    'default': db_config,
}

# Caches
# https://docs.djangoproject.com/en/4.2/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_USERNAME')}:{os.environ.get('REDIS_PASSWORD')}@containers-us-west-43.railway.app:6057",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

CRISPY_TEMPLATE_PACK = "tailwind"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "adminview"

# Message Tags for form messages
MESSAGE_TAGS = {
        messages.DEBUG: 'text-sm text-yellow-700',
        messages.INFO: 'text-sm text-blue-700',
        messages.SUCCESS: 'text-sm font-medium text-green-800',
        messages.WARNING: 'text-sm text-yellow-700',
        messages.ERROR: 'text-sm text-red-700',
}